// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// add_vectors
NumericVector add_vectors(NumericVector vec_a, NumericVector vec_b);
RcppExport SEXP _torchvision_add_vectors(SEXP vec_aSEXP, SEXP vec_bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type vec_a(vec_aSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type vec_b(vec_bSEXP);
    rcpp_result_gen = Rcpp::wrap(add_vectors(vec_a, vec_b));
    return rcpp_result_gen;
END_RCPP
}
// add_matrices
NumericMatrix add_matrices(NumericMatrix mat_a, NumericMatrix mat_b);
RcppExport SEXP _torchvision_add_matrices(SEXP mat_aSEXP, SEXP mat_bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type mat_a(mat_aSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type mat_b(mat_bSEXP);
    rcpp_result_gen = Rcpp::wrap(add_matrices(mat_a, mat_b));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_torchvision_add_vectors", (DL_FUNC) &_torchvision_add_vectors, 2},
    {"_torchvision_add_matrices", (DL_FUNC) &_torchvision_add_matrices, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_torchvision(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
