# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Array Operations (C++ implementation)
#'
#' Element-wise addition of two numeric vectors and matrices using C++.
#'
#' @param vec_a First numeric vector
#' @param vec_b Second numeric vector
#'
#' @return A numeric vector with element-wise sums
#'
#' @details
#' Both vectors must have the same length.
#' If lengths differ, the function will recycle elements.
#'
#' @examples
#' \dontrun{
#' #Vector addition with recycling
#' add_vectors(c(1, 2, 3), c(4, 5, 6))  # Returns c(5, 7, 9)
#'
#' #Matrix addition
#' mat1 <- matrix(1:4, nrow = 2)
#' mat2 <- matrix(5:8, nrow = 2)
#' add_matrices(mat1, mat2)
#' }
#' @name array_ops
#' @export
add_vectors <- function(vec_a, vec_b) {
    .Call(`_torchvision_add_vectors`, vec_a, vec_b)
}

#' @param mat_a First numeric matrix
#' @param mat_b Second numeric matrix  
#'
#' @return A numeric matrix with element-wise sums
#'
#' @details
#' Both matrices must have the same dimensions.
#' Throws an error if dimensions don't match.
#'
#' @rdname array_ops
#' @export
add_matrices <- function(mat_a, mat_b) {
    .Call(`_torchvision_add_matrices`, mat_a, mat_b)
}

