# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calculate Box Areas (C++)
#'
#' Calculates bounding box areas using C++. Provides performance benefits
#' for very large batches of boxes when working with plain matrices.
#'
#' @param boxes Numeric matrix with N rows and 4 columns (x1, y1, x2, y2)
#' @return Numeric vector of areas
#'
#' @details
#' This is a low-level function. Most users should use \code{box_area_fast()}
#' or \code{box_area()} instead.
#'
#' @export
box_area_cpp <- function(boxes) {
    .Call(`_torchvision_box_area_cpp`, boxes)
}

