name: Convert and upload pre-trained models

on:
  workflow_dispatch:

jobs:
  upload:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v4
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - uses: actions/setup-python@v5
        with:
          python-version: 3.10
      - run: |
          python -m pip install --upgrade pip
          pip install torch torchvision google-cloud-storage
      - run: |
          python tools/convert-models.py
