name: Convert and upload pre-trained models

on:
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: 'auth'
        uses: aws-actions/configure-aws-credentials@main
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}
      - uses: actions/setup-python@v5
        with:
          python-version: 3.10
      - run: |
          python -m pip install --upgrade pip
          pip install torch torchvision boto3
      - run: |
          python tools/convert-models.py
